name: build
on:
  push:
    branches:
      - master # run the action on your project's default branch

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11' # Specify the required Java version

      - name: 'Grant execute permission for gradlew'
        run: chmod +x ./gradlew

      - name: 'Verify Gradle Wrapper'
        run: ./gradlew --version

      - name: 'Run Gradle Dependencies Task'
        run: ./gradlew :dependencies --configuration compileClasspath

      - name: Root Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          use-gradlew: true  # Use the Gradle wrapper
          gradle-build-module: ':'
          gradle-build-configuration: 'compileClasspath'
